on: push

name: CI
jobs:
  test_job:
    runs-on: self-hosted
    environment: test
    steps:
      -
        name: Checkout code
        uses: actions/checkout@master
      - name: Build image and push to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: MatiasManevi/test-sh-runners:${{ github.sha }}
